### ISSUE TITLE
Upgrade ByteBuddy to support Java 19

### ISSUE THREAD

**Issue by astubbs** [bsideup/jabel#143]
https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.9

[Byte Buddy 1.12.9](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.9)
Add support for Java 19.

**Comment by bsideup** [comment]
Closed in https://github.com/bsideup/jabel/commit/ff7d10111b2b93686a1a918a3e58e02612e19588
