### ISSUE TITLE
Release version 1.0.0

### ISSUE THREAD

**Issue by asolntsev** [bsideup/jabel#145]
I personally don't like to use version "0.x" in production. It doesn't seem to be serious tool. 

I guess many other users also think so. 
Probably some companies even have policy like "Avoid using 3rd party dependencies of version 0.x". 

@bsideup

**Comment by bsideup** [comment]
Released 🎉

**Comment by asolntsev** [comment]
Wow. Yes. Nice. Great. 

Thanks @bsideup !
