### ISSUE TITLE
Using String methods

### ISSUE THREAD

**Issue by mikolajkania** [bsideup/jabel#21]
Hello, thank you for great project! I have a question - I encountered a problem that I can't use String methods like strip or repeat in code, because it ends with compilation error and message: "java: cannot find symbol". 

I am using JDK13 for compilation, JDK10 as release & Intellij Idea.

**Comment by bsideup** [comment]
Hi @mikolajkania,

Thank you for the positive feedback!

Jabel is a compile-time tool that retrofits the *syntax*, not runtime. Runtime polyfills would be a library on its own :)

See #3 for the discussion. I will close this one as a duplicate, but feel free to join the conversation there 👍
