### ISSUE TITLE
Make target to java 11

### ISSUE THREAD

**Issue by rverma-jm** [bsideup/jabel#22]
Java 8 target is getting redundant and probably tough to maintain when using java 14+. Since the next java lets java 17 seems distant at this point it would be nice to support all intermediate release s to current LTS.

**Comment by bsideup** [comment]
Jabel _lowers_ the minimum requirement to the lowest possible (Java 8), but you can target Java 9, 10, 11 or any other version you want.

**Comment by mdproctor** [comment]
I cannot seem from the code what happens if you set the target to java 11, i.e. where does it know to not rewrite language features between java 8 and java 11. We do not want it to keep rewriting stuff to java 8,  between the ranges of java 8 and java 11, and have potential inefficiencies.

**Comment by bsideup** [comment]
@mdproctor Jabel does not rewrite any code, but _lowers_ the language requirement for certain features. You can set the target to any Java version prior the current one, not only to 8.
