### ISSUE TITLE
Support for standard library polyfills

### ISSUE THREAD

**Issue by lqc** [bsideup/jabel#3]
I really like the idea behind this project. What the frontpage does not mention, is that a valid Java 8 bytecode can't still have a hard time running on actual JRE8 because of missing pieces of the standard library like ``List.of()``. 

So the idea is that the plugin could somehow rewrite references of ``java.util.List#of()`` to a different static method in a specially created polyfill library. 

What do you think?

**Comment by bsideup** [comment]
Hi @lqc,

Jabel does not backport the stdlib, only the syntax.

It would be a completely different scope (and some libraries have attempted to do so, e.g. https://github.com/JavaMoney/jsr354-api-bp), and I do not consider doing it right now given the **much** bigger complexity

**Comment by bsideup** [comment]
It also worth mentioning that language features enabled by Jabel do not require any new stdlib methods btw

**Comment by lqc** [comment]
I agree that this is a complex task and most likely not all parts of stdlib could be pollyfilled this way. 

Maybe providing a hook for other plugins to rewrite static stdlib references? A lot of useful things fall into this category: ``List/Map.of``, ``Optional.stream()``, ``Optional.or()``, etc. This is different then JSR-354 or https://www.threeten.org/threetenbp/ because those are separate packages - you can just include them on older JVM. You can't do the same with ``List#of()``

**Comment by cruftex** [comment]
> A lot of useful things fall into this category: List/Map.of, Optional.stream(), Optional.or(), etc.

Just have the spark of an idea: For simple things like the above it would be possible to create refactoring rules via: https://errorprone.info/docs/refaster

**Comment by tlinkowski** [comment]
Hi, you might be interested in [UniJ](https://github.com/tlinkowski/UniJ), which provides a backport of JDK 9+ APIs in the form of a facade.

E.g. `UniLists.of(1, 2)` corresponds to `List.of(1, 2)`. At runtime, it delegates to:
- either `List.of(1, 2)` (for JDK 9+)
- or `Collections.unmodifiableList(Arrays.asList(1, 2))` (for JDK 8)

If:
- you added a dependency on UniJ
- and Jabel could rewrite `List.of` references into `UniLists.of` ones

you'd achieve the effect you want.

Instance methods (like `Optional.stream()`) would be much more problematic to rewrite, though.

Disclaimer: I'm the author of UniJ.
