### ISSUE TITLE
Troubles with Jabel 0.3.0

### ISSUE THREAD

**Issue by AlexRomanch** [bsideup/jabel#49]
Hi!
trying to use Jabel 0.3.0 with gradle settings:
```groovy
sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_1_8

tasks.withType(JavaCompile).all {
	options.compilerArgs = [
			"--release", "8", // Avoid using Java 9+ APIs
			"--enable-preview",
	]

	doFirst {
		options.compilerArgs = options.compilerArgs.findAll {
			it != "--enable-preview"
		}
	}
}

dependencies {
	annotationProcessor "com.github.bsideup.jabel:jabel-javac-plugin:0.3.0"
}
```

and i get an error on compileJava (on var usage).

But when i downgrade jabel version to 0.2.0 i see 
```groovy
Jabel: initialized. Enabled features: 
	- DIAMOND_WITH_ANONYMOUS_CLASS_CREATION
	- PRIVATE_SAFE_VARARGS
	- EFFECTIVELY_FINAL_VARIABLES_IN_TRY_WITH_RESOURCES
	- LOCAL_VARIABLE_TYPE_INFERENCE
```
and it work correct.

What can be wrong with settings for 0.3.0? Please advise.

**Comment by bsideup** [comment]
Hi @AlexRomanch,

Could you please share an example project that reproduces the issue?

**Comment by AlexRomanch** [comment]
Hi @bsideup ,
Please, watch it:
[jabel-test.zip](https://github.com/bsideup/jabel/files/5392874/jabel-test.zip)

**Comment by AlexRomanch** [comment]
@bsideup for convenience, i have uploaded the project to github:
https://github.com/AlexRomanch/jabel-test

Tell me please, is it trouble in my settings or in Jabel?

**Comment by bsideup** [comment]
@AlexRomanch thanks! I indeed forgot to mention that, on Java <= 13, you need to enable the plugin explicitly:
https://github.com/bsideup/jabel/commit/7b12cb75a63abc8ab3eb5d4e9f6211c16f5882c9

Sorry for that! Let me know if it doesn't help :)

**Comment by AlexRomanch** [comment]
@bsideup thank you! it works for simple java app.
But when i tried to use it in Spring Boot application - getting an error on compileJava with message "plug-in not found: jabel".
Build.gradle:
```gradle
plugins {
	id 'org.springframework.boot' version '2.2.5.RELEASE'
	id 'io.spring.dependency-management' version '1.0.10.RELEASE'
	id 'java'
}
group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_1_8

tasks.withType(JavaCompile).all {
	options.compilerArgs = [
			"--release", "8", // Avoid using Java 9+ APIs
			'--enable-preview',
	]
	options.compilerArgs << '-Xplugin:jabel'

	doFirst {
		options.compilerArgs = options.compilerArgs.findAll {
			it != '--enable-preview'
		}
	}
}
repositories {
	mavenCentral()
}
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
	annotationProcessor 'com.github.bsideup.jabel:jabel-javac-plugin:0.3.0'
}

```

Example (simple Spring Boot project, generated using Spring Initializr):
https://github.com/AlexRomanch/jabel-spring-demo

Any ideas?

**Comment by AlexRomanch** [comment]
@bsideup tell me please, should Jabel work with Spring Boot 2.2? or there are troubles with build.gradle (in previous comment)?

**Comment by AlexRomanch** [comment]
I tried to add buildscipt and apply plugin:
```gradle
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath "com.github.bsideup.jabel:jabel-javac-plugin:0.3.0"
	}
}

apply plugin: 'jabel-javac-plugin'

```

doesn't help.

**Comment by bsideup** [comment]
@AlexRomanch since `tasks.withType(JavaCompile).all` is used, you need to also add Jabel to `testAnnotationProcessor` - unfortunately, Gradle does not inherit it automatically.

And yes, Jabel should work perfectly fine with any Java project, Spring Boot included.

**Comment by AlexRomanch** [comment]
@bsideup it work. Thank you so much!
I think it wiil be useful to add information about `testAnnotationProcessor` to readme.

**Comment by bsideup** [comment]
@AlexRomanch thanks for reporting! I'm thinking about reworking the Gradle example a bit, so that it is more "focused" on the main source (with some hints on how to get Jabel work with the test classpath, too)
