### ISSUE TITLE
Add IntelliJ IDEA setting to avoid using Java 9+ APIs in README

### ISSUE THREAD

**Issue by linux-china** [bsideup/jabel#5]
How to avaoid using Java 9+ APIs with IntelliJ IDEA. 

Open Settings, choose "Inspection" , find "Usages of API which isn't avaiable at the configured language level",   click "Higher than", and choose "9 - Modules, private method in interfaces etc". 

![image](https://user-images.githubusercontent.com/46711/64408164-aad29c80-d0b8-11e9-9496-5f73b1ced309.png)

**Comment by bsideup** [comment]
@linux-china that's a very nice finding! 👍 

Would you like to contribute it to README? :)
We could have an "IDE support" section with such hints

**Comment by bsideup** [comment]
Closed by #6
