### ISSUE TITLE
Doesn't work on Java 16

### ISSUE THREAD

**Issue by IMS212** [bsideup/jabel#58]
`Caused by: java.lang.IllegalAccessError: class com.github.bsideup.jabel.JabelCompilerPlugin (in unnamed module @0x7f3097e8) cannot access class com.sun.tools.javac.code.Source$Feature (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x7f3097e8`

This is likely due to [JEP 396](https://openjdk.java.net/jeps/396).

**Comment by lukaseder** [comment]
I also ran into this just now, when I tried to introduce jabel to replace my own regex based backports :)

**Comment by bsideup** [comment]
@lukaseder oh, that's unfortunate 😅 

I will have a look this weekend 👍

**Comment by xxDark** [comment]
https://github.com/xxDark/deencapsulation

May be used as a workaround

**Comment by Username404-59** [comment]
To use 0.3.0 with java 16 you can add the following flags:
"--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
"--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED"
to the forkOptions.jvmArgs of JavaCompile tasks, set isFork to true and update byte-buddy to the 1.10.22 version

**Comment by Treehopper** [comment]
@Username404-59  trying to get your workaround to fly with Maven, but I guess I am missing something. Any idea?
```
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.1</version>
                    <configuration>
                        <release>16</release>
                        <annotationProcessorPaths>
                            <annotationProcessorPath>
                                <groupId>com.github.bsideup.jabel</groupId>
                                <artifactId>jabel-javac-plugin</artifactId>
                                <version>0.3.0</version>
                            </annotationProcessorPath>
                        </annotationProcessorPaths>

                        <fork>true</fork>
                        <compilerArgs>
                            <arg>--add-opens</arg>
                            <arg>jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</arg>
                            <arg>--add-opens</arg>
                            <arg>jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</arg>
                        </compilerArgs>
                    </configuration>

                    <dependencies>
                        <dependency>
                            <groupId>net.bytebuddy</groupId>
                            <artifactId>byte-buddy</artifactId>
                            <version>1.10.22</version>
                        </dependency>
                        <dependency>
                            <groupId>net.bytebuddy</groupId>
                            <artifactId>byte-buddy-agent</artifactId>
                            <version>1.10.22</version>
                        </dependency>
                    </dependencies>
                </plugin>
```
Thanks!

**Comment by Username404-59** [comment]
@Treehopper I'm not really familiar with maven but I think it should probably work, maybe you could try replacing --add-opens with --add-exports since you're using compiler arguments ?
