### ISSUE TITLE
How to use Jabel with gradle toolchains ?

### ISSUE THREAD

**Issue by Username404-59** [bsideup/jabel#62]
Gradle toolchains do not allow the sourceCompatibility to be set, and are probably setting the options.release property of JavaCompile tasks; is there a way to get syntax highlighting in this context ?

**Comment by bsideup** [comment]
Hi @Username404-59,

We just documented how to use Jabel with toolchains:
https://github.com/bsideup/jabel/commit/1820e1ea41e87547cf88b46624d15e2f07ca7949

**Comment by Username404-59** [comment]
Thanks, It works perfectly!
